sra points out the django south check needs to avoid lexographic comparison of version numbers
closes #348

svn path=/trunk/; revision=4872

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4369,7 +4369,7 @@ $as_echo "$have_django_south" >&6; }
 	then
 		{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for Django South 0.7.6 or later" >&5
 $as_echo_n "checking for Django South 0.7.6 or later... " >&6; }
-		have_acceptable_django_south=`$PYTHON -c "import south; print 'no' if south.__version__ < '0.7.6' else 'yes'"`
+		have_acceptable_django_south=`$PYTHON -c "import south; print 'no' if map(int,south.__version__.split('.')) < [0, 7, 6] else 'yes'"`
 		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $have_acceptable_django_south" >&5
 $as_echo "$have_acceptable_django_south" >&6; }
 	fi
@@ -4418,16 +4418,19 @@ $as_echo "$as_me: WARNING: The RPKI CA tools require Django 1.2 or higher." >&2;
 			{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: The RPKI CA GUI requires the Python vobject module" >&5
 $as_echo "$as_me: WARNING: The RPKI CA GUI requires the Python vobject module" >&2;}
 		fi
-		if test $ok = no
-		then
-			{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: If you do not wish to install the RPKI CA tools, please specify --disable-ca-tools as an argument to this configure script." >&5
-$as_echo "$as_me: WARNING: If you do not wish to install the RPKI CA tools, please specify --disable-ca-tools as an argument to this configure script." >&2;}
-		fi
 		if test $have_acceptable_django_south = no
 		then
 			ok=no
 			{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: The RPKI CA tools require Django South 0.7.6 or higher." >&5
 $as_echo "$as_me: WARNING: The RPKI CA tools require Django South 0.7.6 or higher." >&2;}
+		fi
+		#
+		# This should be the last test in this group, so that failures get the --disable-ca-tools warning.
+		#
+		if test $ok = no
+		then
+			{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: If you do not wish to install the RPKI CA tools, please specify --disable-ca-tools as an argument to this configure script." >&5
+$as_echo "$as_me: WARNING: If you do not wish to install the RPKI CA tools, please specify --disable-ca-tools as an argument to this configure script." >&2;}
 		fi
 		;;
      no)	build_ca_tools=no
