give the user explanatory feedback about why django is required when configure can't find it installed.  closes #150.
svn path=/trunk/; revision=4094

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4814,14 +4814,14 @@ case $enable_django in
      yes)	build_django=yes
 		if test $have_django = no
 		then
-			{ { $as_echo "$as_me:$LINENO: error: You don't appear to have Django installed" >&5
-$as_echo "$as_me: error: You don't appear to have Django installed" >&2;}
+			{ { $as_echo "$as_me:$LINENO: error: You don't appear to have Django installed.  Django is required for the RPKI portal gui.  If you do not wish to install the gui, please specify --disable-django as an argument to this configure script." >&5
+$as_echo "$as_me: error: You don't appear to have Django installed.  Django is required for the RPKI portal gui.  If you do not wish to install the gui, please specify --disable-django as an argument to this configure script." >&2;}
    { (exit 1); exit 1; }; }
 		fi
 		if test $django_recent = no
 		then
-			{ { $as_echo "$as_me:$LINENO: error: The portal gui requires Django 1.3 or higher" >&5
-$as_echo "$as_me: error: The portal gui requires Django 1.3 or higher" >&2;}
+			{ { $as_echo "$as_me:$LINENO: error: The portal gui requires Django 1.2 or higher" >&5
+$as_echo "$as_me: error: The portal gui requires Django 1.2 or higher" >&2;}
    { (exit 1); exit 1; }; }
 		fi
 		;;
